name: python-setup
on:
        push:
jobs:
        python-setup:
                runs-on: ubuntu-latest
                steps:
                        - name: checkout respository
                          uses: actions/checkout@v4
                        - name: Setup Python 3.9
                          uses: actions/setup-python@v4
                          with:
                                  python-version: '3.9'
                        - name: Install dependencies
                          run: pip install pytest flake8
                        - name: Verify Python version
                          run: python --version
                        - name: Verify Flake8
                          run: flake8 --version
                        - name: Verify Pytest
                          run: pytest --version  
